version: 0.1           
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region ap-northeast-1)
  build:
    commands:
      - docker build --tag "${REPOSITORY}:v02" . 
  post_build:
    commands:
      - docker push "${REPOSITORY}:v02"
      - printf '{"Image":"%s:%s"}' $REPOSITORY v02 > build.json
artifacts:
  files:
    - build.json
    - cfn/service.yml
    - cfn/environments/production.json
  discard-paths: yes