version: 0.1           
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - docker build --tag "${REPOSITORY}:v05" . 
  post_build:
    commands:
      - docker push "${REPOSITORY}:v05"
      - printf '{"Image":"%s:%s"}' $REPOSITORY v05 > build.json
artifacts:
  files:
    - build.json
    - cfn/service.yml
    - cfn/environments/production.json
  discard-paths: yes