--- 
Parameters: 
  Cluster: 
    Type: String
  DesiredCount: 
    Type: String
  Image: 
    Type: String
  Role: 
    Type: String
  TargetGroupArn: 
    Type: String
Resources: 
  Service: 
    Properties: 
      Cluster: Cluster
      DeploymentConfiguration: 
        - 
          MaximumPercent: 100
          MinimumHealthyPercent: 33
      DesiredCount: DesiredCount
      LoadBalancers: 
        - 
          ContainerName: node
          ContainerPort: 80
          TargetGroupArn: TargetGroupArn
      Role: Role
      TaskDefinition: TaskDefinition
    Type: "AWS::ECS::Service"
  TaskDefinition: 
    Properties: 
      ContainerDefinitions: 
        - 
          Image: Image
          Memory: 512
          Name: node
          PortMappings: 
            - 
              ContainerPort: 80
      Family: Service
    Type: "AWS::ECS::TaskDefinition"
